global:
  scrape_interval: 5s

scrape_configs:
  - job_name: core-api-express
    static_configs:
      - targets: [ 'text-rl-core-api-express:5000' ]
  - job_name: core-api-express-localhost
    static_configs:
      - targets: [ 'host.docker.internal:5000' ]
  - job_name: treatment-app
    static_configs:
      - targets: [ 'treatment-app:8080' ]
  - job_name: treatment-app-localhost
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
  - job_name: node-exporter-express
    static_configs:
      - targets: [ 'text-rl-core-api-express:9100' ]
  - job_name: core-api-net
    static_configs:
      - targets: [ 'text-rl-core-api-net:5000' ]
  - job_name: core-api-net-localhost
    static_configs:
      - targets: [ 'host.docker.internal:5001' ]
  - job_name: node-exporter-net
    static_configs:
      - targets: [ 'text-rl-core-api-net:9100' ]
  - job_name: text-rl-db-mssql-exporter
    static_configs:
      - targets: [ 'text-rl-db-mssql-exporter:9399' ]
  - job_name: text-rl-db-mysql-exporter
    static_configs:
      - targets: [ 'text-rl-db-mysql-exporter:9104' ]
